---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - events
  - persistentvolumeclaims
  - persistentvolumes
  - pods
  - pods/exec
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  - pods/logs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - db.tarantool.io
  resources:
  - clusters
  - replicasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - db.tarantool.io
  resources:
  - clusters/finalizers
  - replicasets/finalizers
  verbs:
  - update
- apiGroups:
  - db.tarantool.io
  resources:
  - clusters/status
  - replicasets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tarantool.io
  resources:
  - cartridgeconfigs
  - clusters
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tarantool.io
  resources:
  - cartridgeconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - tarantool.io
  resources:
  - cartridgeconfigs/status
  - clusters/status
  - roles/status
  verbs:
  - get
  - patch
  - update
