// Package clusterconfig renders a Tarantool 3 declarative cluster
// configuration from the operator's v2alpha1 CRDs.
//
// It maps a Cluster plus its ReplicaSets onto the Tarantool 3 configuration
// tree (global scope -> groups -> replicasets -> instances) and serializes it to
// YAML. The configuration is delivered to Tarantool verbatim and validated by
// Tarantool itself (see marshalTree), so the renderer does no schema validation.
//
// Serialization note: the tree is serialized with sigs.k8s.io/yaml (the same
// codec ParseDelivered reads back with), which marshals via JSON and so emits
// keys in sorted order. Tarantool does not care about key order; consumers that
// need to detect change (the config-Secret reconciler and the pod-rollout
// trigger) hash a canonical form (hashTree / the scope hashes), never the raw
// bytes. Tests likewise compare parsed structures.
//
// The renderer is intentionally pure: it takes already-resolved inputs (no
// Kubernetes client, no Secret lookups) so it can be exhaustively unit-tested.
// The controller resolves Secret values and hands them in via Input.Passwords.
package clusterconfig

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"

	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"sigs.k8s.io/yaml"

	"github.com/tarantool/tarantool-operator/apis/v2alpha1"
)

// Roles recognized when wiring advertise logins.
const (
	roleReplication = "replication"
	roleSharding    = "sharding"
)

// AdminSocketPath is where each instance exposes its admin console socket. The
// readiness probe connects here to query box.info without authentication; the
// path lives in /var/run/tarantool, which the tarantool image creates writable.
const AdminSocketPath = "/var/run/tarantool/admin.socket"

// OperatorUser is the operator's built-in privileged Tarantool user. Unless
// Cluster.spec.disableOperatorUser is set, the renderer declares it with the
// super role (password generated by the controller into the
// <cluster>-operator-user Secret), so the operator's iproto features work out
// of the box. A user-declared credentials.users entry of the same name wins.
// (Dashes are valid in Tarantool user names — verified against tarantool 3.)
const OperatorUser = "tarantool-operator"

// Input is the resolved data the renderer needs to produce a cluster config.
type Input struct {
	// Cluster carries the cluster-wide (global scope) configuration.
	Cluster *v2alpha1.Cluster

	// ReplicaSets are the replicasets belonging to Cluster. ReplicaSets whose
	// spec.clusterName does not match Cluster.Name are ignored.
	ReplicaSets []v2alpha1.ReplicaSet

	// Passwords maps a credential user name to the plaintext password resolved
	// from its Secret. Users without an entry are rendered without a password.
	Passwords map[string]string
}

// ConfigHashLabel is a global label the renderer stamps with the config's content
// hash. Tarantool exposes labels via require('config'):get('labels'), so the
// operator can connect to an instance after pushing a new config and confirm it
// has loaded that exact version (the operator-driven config:reload() path).
const ConfigHashLabel = "operator_config_hash"

// Render builds the full Tarantool 3 declarative configuration for the Cluster
// and its ReplicaSets and returns it as YAML.
func Render(in Input) ([]byte, error) {
	rendered, _, err := RenderAndHash(in)
	return rendered, err
}

// hashTree computes the canonical content hash of an already-built config tree.
// Render's YAML output is not byte-stable (go-config preserves map iteration
// order), so change detection uses this hash of the key-sorted JSON encoding:
// equal configurations always hash equally.
func hashTree(tree map[string]any) (string, error) {
	canonical, err := json.Marshal(tree)
	if err != nil {
		return "", fmt.Errorf("clusterconfig: hashing config: %w", err)
	}

	sum := sha256.Sum256(canonical)
	return hex.EncodeToString(sum[:]), nil
}

// RenderAndHash builds the config tree once and returns both the rendered YAML and
// its canonical change-detection hash. The rendered config carries the hash as the
// global ConfigHashLabel so instances report which version they are running; the
// hash itself is computed over the label-less tree (so it is stable and not
// self-referential). The controller uses this on the hot reconcile path instead of
// calling Render and Hash separately, which would build the tree twice.
func RenderAndHash(in Input) (rendered []byte, hash string, err error) {
	tree, err := buildTree(in)
	if err != nil {
		return nil, "", err
	}
	hash, err = hashTree(tree)
	if err != nil {
		return nil, "", err
	}
	setConfigHashLabel(tree, hash)
	rendered, err = marshalTree(tree)
	if err != nil {
		return nil, "", err
	}
	return rendered, hash, nil
}

// setConfigHashLabel stamps the content hash into the global labels section,
// preserving any user-provided labels.
func setConfigHashLabel(tree map[string]any, hash string) {
	labels, _ := tree["labels"].(map[string]any)
	if labels == nil {
		labels = map[string]any{}
		tree["labels"] = labels
	}
	labels[ConfigHashLabel] = hash
}

// marshalTree serializes the assembled tree to YAML. The configuration is NOT
// validated here: Tarantool itself is the authority on what is valid (it
// validates the config on start and on config:reload(), and the schema differs
// across versions), so the operator passes the tree through verbatim. A bad
// config surfaces as an instance-side error rather than being second-guessed by
// an operator-pinned schema copy. (sigs.k8s.io/yaml is the same YAML codec
// ParseDelivered reads the rendered config back with.)
func marshalTree(tree map[string]any) ([]byte, error) {
	out, err := yaml.Marshal(tree)
	if err != nil {
		return nil, fmt.Errorf("clusterconfig: marshalling config: %w", err)
	}
	return out, nil
}

// buildTree assembles the nested Tarantool 3 configuration map.
func buildTree(in Input) (map[string]any, error) {
	if in.Cluster == nil {
		return nil, fmt.Errorf("clusterconfig: nil Cluster")
	}

	c := in.Cluster
	root := map[string]any{}

	ucfg, err := parseUserCfg(c, nil)
	if err != nil {
		return nil, err
	}

	// Global iproto advertise: tell instances which user to authenticate as for
	// peer (replication) and, when sharded, for vshard traffic. The users come
	// from the user's config (credentials.users at the global scope).
	iproto := map[string]any{}
	if login := ucfg.userWithRole(roleReplication); login != "" {
		iproto["advertise"] = map[string]any{"peer": map[string]any{"login": login}}
	}
	if login := ucfg.userWithRole(roleSharding); login != "" {
		adv, _ := iproto["advertise"].(map[string]any)
		if adv == nil {
			adv = map[string]any{}
			iproto["advertise"] = adv
		}
		adv["sharding"] = map[string]any{"login": login}
	}
	if len(iproto) > 0 {
		root["iproto"] = iproto
	}

	// Admin console socket, used by the pod readiness probe to read box.info
	// over the local (unauthenticated) console.
	root["console"] = map[string]any{
		"enabled": true,
		"socket":  AdminSocketPath,
	}

	groups, err := buildGroups(c, in.ReplicaSets)
	if err != nil {
		return nil, err
	}
	if len(groups) > 0 {
		root["groups"] = groups
	}

	// Merge the cluster-scope passthrough config underneath operator-managed
	// keys (operator keys win on conflict).
	if c.Spec.Config != nil {
		extra, err := jsonToMap(c.Spec.Config)
		if err != nil {
			return nil, fmt.Errorf("clusterconfig: cluster spec.config: %w", err)
		}
		mergeUnderlay(root, extra)
	}

	// Built-in operator user: declared after the user's config is merged so a
	// user-declared user of the same name wins verbatim. Its password arrives
	// through in.Passwords like any other user's (injectPasswords below).
	if !c.Spec.DisableOperatorUser {
		injectOperatorUser(root)
	}

	// Inject Secret-resolved passwords for users declared in the config
	// (global-scope credentials.users) that carry none inline, so passwords live
	// in a Kubernetes Secret rather than the CR. An inline password wins.
	injectPasswords(root, in.Passwords)

	return root, nil
}

// injectOperatorUser declares the built-in OperatorUser with the super role,
// unless the user already declared a user of that name (their definition wins).
func injectOperatorUser(root map[string]any) {
	creds, _ := root["credentials"].(map[string]any)
	if creds == nil {
		creds = map[string]any{}
		root["credentials"] = creds
	}
	users, _ := creds["users"].(map[string]any)
	if users == nil {
		users = map[string]any{}
		creds["users"] = users
	}
	if _, exists := users[OperatorUser]; exists {
		return
	}
	users[OperatorUser] = map[string]any{"roles": []any{"super"}}
}

// injectPasswords fills credentials.users.<name>.password from passwords for
// users that have no inline password.
func injectPasswords(root map[string]any, passwords map[string]string) {
	users, _ := lookup(root, "credentials", "users").(map[string]any)
	for name, u := range users {
		um, ok := u.(map[string]any)
		if !ok {
			if u == nil { // `user: {}` parsed as nil
				um = map[string]any{}
				users[name] = um
			} else {
				continue
			}
		}
		if _, has := um["password"]; has {
			continue
		}
		if pw, ok := passwords[name]; ok && pw != "" {
			um["password"] = pw
		}
	}
}

// buildGroups groups the ReplicaSets by their configuration group and renders
// each replicaset under groups.<group>.replicasets.<name>.
func buildGroups(c *v2alpha1.Cluster, replicaSets []v2alpha1.ReplicaSet) (map[string]any, error) {
	groups := map[string]any{}

	for i := range replicaSets {
		rs := &replicaSets[i]
		if rs.Spec.ClusterName != c.Name {
			continue
		}

		group, _ := groups[rs.GetGroup()].(map[string]any)
		if group == nil {
			group = map[string]any{}
			groups[rs.GetGroup()] = group
		}

		replicasets, _ := group["replicasets"].(map[string]any)
		if replicasets == nil {
			replicasets = map[string]any{}
			group["replicasets"] = replicasets
		}

		rsTree, err := buildReplicaSet(c, rs)
		if err != nil {
			return nil, err
		}
		replicasets[rs.Name] = rsTree
	}

	// Raw group-scope config: placed under groups.<name>; Tarantool applies scope
	// precedence itself. Only groups that exist (have ReplicaSets) are rendered.
	for name := range c.Spec.GroupConfigs {
		group, ok := groups[name].(map[string]any)
		if !ok {
			continue
		}
		raw := c.Spec.GroupConfigs[name]
		extra, err := jsonToMap(&raw)
		if err != nil {
			return nil, fmt.Errorf("clusterconfig: group %q config: %w", name, err)
		}
		mergeUnderlay(group, extra)
	}

	return groups, nil
}

// buildReplicaSet renders one replicaset: the operator's bootstrap wiring, the
// generated instances, and the user's raw config sections. Tarantool semantics
// (failover, sharding, roles, ...) come entirely from the user's config; the
// operator consults them (via userCfg) only for the wiring its own defaults
// depend on.
func buildReplicaSet(c *v2alpha1.Cluster, rs *v2alpha1.ReplicaSet) (map[string]any, error) {
	m := map[string]any{}

	ucfg, err := parseUserCfg(c, rs)
	if err != nil {
		return nil, err
	}
	group := rs.GetGroup()

	// Deterministic initial bootstrap: designate the first instance as the
	// bootstrap leader. A fresh multi-instance replicaset otherwise deadlocks —
	// the replicator user only exists after an instance bootstraps, so with the
	// default "auto" strategy peers loop on authentication waiting for each
	// other. After bootstrap, the cluster failover mode governs runtime
	// leadership. bootstrap_leader is a replicaset-scope field (sibling of
	// instances/leader); bootstrap_strategy lives under replication and merges
	// with the global replication scope (which carries failover).
	m["bootstrap_leader"] = rs.InstanceName(0)
	replication := map[string]any{
		"bootstrap_strategy": "config",
	}
	// Gracefully expel instances dropped from the config on scale-down
	// (Tarantool >= 3.3): when an instance is removed and the cluster reconfigures,
	// the leader deletes it from _cluster instead of leaving an orphan in
	// box.info.replication. Scoped by the replicaset-name prefix, which matches this
	// replicaset's instance names (<rs>-<ordinal>).
	//
	// Only enabled once the replica set has bootstrapped (Status.Bootstrapped). At
	// fresh, concurrent bootstrap autoexpel races the join protocol and can expel
	// peers — every instance ends up in its own replica set (split-brain, verified
	// in the kind e2e). Gating on the sticky Bootstrapped flag means autoexpel turns
	// on only after the set has fully formed, where it safely serves scale-down.
	if rs.Status.Bootstrapped {
		replication["autoexpel"] = map[string]any{
			"enabled": true,
			"by":      "prefix",
			"prefix":  rs.Name,
		}
	}
	m["replication"] = replication

	// A replica set must declare a writable instance, or every instance defaults
	// to read-only and a fresh replica set fails to bootstrap with "No leader to
	// register new instance" (verified against tarantool 3.7). The failover mode
	// comes from the user's config (default "off"); the operator only fills the
	// gaps the user left:
	//   - manual: default the replicaset leader to the first instance when the
	//     user named none;
	//   - off: make the first instance writable via database.mode when the user
	//     set no mode anywhere — at a broader scope or on ANY instance (if the
	//     user designated, say, ordinal 1 as rw, generating a second writer on
	//     ordinal 0 would split writes);
	//   - election/supervised: Tarantool elects/coordinates the leader.
	failover := ucfg.str(group, "", FailoverOff, "replication", "failover")
	rwInstance := ""
	switch failover {
	case FailoverManual:
		if ucfg.chain(group, "").value("leader") == nil {
			m["leader"] = rs.InstanceName(0)
		}
	case FailoverOff:
		if !ucfg.hasAnyDatabaseMode(group) {
			rwInstance = rs.InstanceName(0)
		}
	}

	instances := map[string]any{}
	for ordinal := int32(0); ordinal < rs.GetReplicas(); ordinal++ {
		name := rs.InstanceName(ordinal)
		inst := buildInstance(c, rs, ucfg, ordinal)
		if name == rwInstance {
			inst["database"] = map[string]any{"mode": "rw"}
		}
		// Raw instance-scope config, keyed by ordinal. Operator-generated keys
		// (advertise URI, listen) win on conflict; ordinals beyond replicas-1 are
		// ignored because only generated instances exist.
		if raw, ok := rs.Spec.InstanceConfigs[fmt.Sprint(ordinal)]; ok {
			extra, err := jsonToMap(&raw)
			if err != nil {
				return nil, fmt.Errorf("clusterconfig: replicaset %q instance %d config: %w", rs.Name, ordinal, err)
			}
			mergeUnderlay(inst, extra)
		}
		instances[name] = inst
	}
	m["instances"] = instances

	if rs.Spec.Config != nil {
		extra, err := jsonToMap(rs.Spec.Config)
		if err != nil {
			return nil, fmt.Errorf("clusterconfig: replicaset %q spec.config: %w", rs.Name, err)
		}
		mergeUnderlay(m, extra)
	}

	// A sharded storage replica set pending deletion renders with sharding.weight
	// 0, so vshard drains its buckets onto the remaining storages before the
	// drain-gated finalizer lets the delete proceed — no buckets are lost. Only
	// touches storages (a sharding section with the "storage" role); routers and
	// non-sharded sets are unaffected.
	if rs.DeletionTimestamp != nil {
		if sh, ok := m["sharding"].(map[string]any); ok && hasStorageRole(sh["roles"]) {
			sh["weight"] = 0
		}
	}

	return m, nil
}

// hasStorageRole reports whether a sharding.roles value contains "storage".
func hasStorageRole(roles any) bool {
	list, _ := roles.([]any)
	for _, r := range list {
		if r == "storage" {
			return true
		}
	}
	return false
}

// buildInstance renders a single instance's Kubernetes wiring: where it binds
// (listen) and the stable DNS name peers use to reach it (advertise.peer.uri —
// the StatefulSet pod FQDN, which equals the instance name). When the user
// configured iproto.listen themselves (at any scope), the operator generates no
// listen — Tarantool's instance-scope precedence would shadow it and arrays
// replace rather than merge — and derives the advertise port from the user's
// URI (default 3301, the operator's convention; Tarantool has no default
// listen).
func buildInstance(c *v2alpha1.Cluster, rs *v2alpha1.ReplicaSet, ucfg userCfg, ordinal int32) map[string]any {
	group := rs.GetGroup()
	ord := fmt.Sprint(ordinal)
	port := ucfg.listenPort(group, ord, DefaultIprotoPort)
	uri := fmt.Sprintf(
		"%s.%s.%s.svc.%s:%d",
		rs.InstanceName(ordinal), c.Name, c.Namespace, c.GetDomain(), port,
	)

	advertise := map[string]any{
		"peer": map[string]any{"uri": uri},
	}
	// In a sharded cluster the global scope carries advertise.sharding.login —
	// which stops sharding from inheriting advertise.peer, so vshard would fall
	// back to the listen URI (0.0.0.0 — "INADDR_ANY cannot be used to create a
	// client socket"). Give sharding the same per-instance DNS URI; the scopes
	// deep-merge into {login, uri}.
	if ucfg.userWithRole(roleSharding) != "" {
		advertise["sharding"] = map[string]any{"uri": uri}
	}

	iproto := map[string]any{"advertise": advertise}
	if !ucfg.hasListen(group, ord) {
		iproto["listen"] = []any{
			map[string]any{"uri": fmt.Sprintf("0.0.0.0:%d", port)},
		}
	}
	return map[string]any{"iproto": iproto}
}

// mergeUnderlay merges under into base without overwriting keys already present
// in base (recursing into nested maps). Base values "win" on conflict.
func mergeUnderlay(base, under map[string]any) {
	for k, uv := range under {
		bv, ok := base[k]
		if !ok {
			base[k] = uv
			continue
		}
		bm, bok := bv.(map[string]any)
		um, uok := uv.(map[string]any)
		if bok && uok {
			mergeUnderlay(bm, um)
		}
	}
}

// jsonToMap decodes a CRD passthrough JSON blob into a map, normalizing JSON
// numbers to int64/float64 so integers serialize cleanly to YAML.
func jsonToMap(j *apiextensionsv1.JSON) (map[string]any, error) {
	if j == nil || len(j.Raw) == 0 {
		return map[string]any{}, nil
	}

	dec := json.NewDecoder(bytes.NewReader(j.Raw))
	dec.UseNumber()

	var m map[string]any
	if err := dec.Decode(&m); err != nil {
		return nil, err
	}

	normalized, _ := normalizeNumbers(m).(map[string]any)
	return normalized, nil
}

// normalizeNumbers walks a decoded JSON value converting json.Number to int64
// when integral, otherwise float64.
func normalizeNumbers(v any) any {
	switch t := v.(type) {
	case map[string]any:
		for k, e := range t {
			t[k] = normalizeNumbers(e)
		}
		return t
	case []any:
		for i, e := range t {
			t[i] = normalizeNumbers(e)
		}
		return t
	case json.Number:
		if n, err := t.Int64(); err == nil {
			return n
		}
		if f, err := t.Float64(); err == nil {
			return f
		}
		return t.String()
	default:
		return v
	}
}
